# Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
# Hibernate Properties
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/proposta
    username: keycloak
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/nosso-cartao}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/nosso-cartao/protocol/openid-connect/certs}
  application:
    name: proposta


#timeouts do Feign
feign:
  client:
    config:
      analise-proposta:
        connect-timeout: 1000
        read-timeout: 1000

#Urls de servicos externos
servicos-externos:
  base-url: http://localhost:9999
  cartoes: http://localhost:8888

##metricas
management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    tags:
      ambiente: ${AMBIENTE:desenvolvimento}
      aplicacao: ${NOME_DA_APLICACAO:serviço de proposta}

#schedue
periodicidade-schedue:
  criar-cartao : 5000
